### ISSUE TITLE
Skipping of defect files

### ISSUE THREAD

**Issue by LeonSaal** [odea-project/qAlgorithms#8]
Hi there,

currently when trying to process a defect file inside a folder, the program exits. I suggest that the file was skipped and remaining files were processed. This should be considered with low priority as its just for convenience.

Kind regards,

Leon

**Comment by dahoehn** [comment]
Hi Leon, 
I will add it as an optional parameter to the next release.
I decided against making skipping the default behaviour so the user does not overlook defective files.

**Comment by dahoehn** [comment]
This feature request has been incorporated into the branch qBinning_beta.
